alter table public.api_usage
  add column is_batch boolean not null default false;

comment on column public.api_usage.is_batch is
  'True if this row was generated by Anthropic Batch API ingest (recordBatchUsage). False for synchronous calls via trackedCall.';

create index api_usage_is_batch_idx on public.api_usage (is_batch)
  where is_batch = true;
