/**
 * Deterministic country-name normalizer and US state lookup.
 * No AI, no external APIs — pure mapping.
 */

// Canonical country names keyed by lowercased variant
const RAW_COUNTRY_MAP: Record<string, string> = {
  // === Aliases ===
  "usa": "United States",
  "us": "United States",
  "u.s.a.": "United States",
  "u.s.a": "United States",
  "u.s.": "United States",
  "united states": "United States",
  "united states of america": "United States",

  "uk": "United Kingdom",
  "u.k.": "United Kingdom",
  "u.k": "United Kingdom",
  "united kingdom": "United Kingdom",
  "england": "United Kingdom",
  "scotland": "United Kingdom",
  "wales": "United Kingdom",
  "northern ireland": "United Kingdom",

  "prc": "China",
  "p.r. china": "China",
  "p.r.china": "China",
  "pr china": "China",
  "people's republic of china": "China",
  "china": "China",

  "republic of korea": "South Korea",
  "south korea": "South Korea",
  "rok": "South Korea",
  "korea": "South Korea",

  "republic of north macedonia": "North Macedonia",
  "rn macedonia": "North Macedonia",
  "r. macedonia": "North Macedonia",
  "republic of macedonia": "North Macedonia",
  "macedonia": "North Macedonia",
  "north macedonia": "North Macedonia",

  "federal republic of germany": "Germany",
  "germany": "Germany",

  "russian federation": "Russia",
  "russia": "Russia",

  "czech republic": "Czech Republic",
  "czechia": "Czech Republic",

  "the netherlands": "Netherlands",
  "holland": "Netherlands",
  "netherlands": "Netherlands",

  // === ISO 3166-1 alpha-2 codes ===
  // (GeoNames geo_cities.country uses these — must translate to full names)
  "af": "Afghanistan",
  "al": "Albania",
  "dz": "Algeria",
  "am": "Armenia",
  "ar": "Argentina",
  "at": "Austria",
  "au": "Australia",
  "az": "Azerbaijan",
  "bh": "Bahrain",
  "bd": "Bangladesh",
  "by": "Belarus",
  "be": "Belgium",
  "bo": "Bolivia",
  "ba": "Bosnia and Herzegovina",
  "br": "Brazil",
  "bg": "Bulgaria",
  "kh": "Cambodia",
  "cm": "Cameroon",
  "ca": "Canada",
  "cl": "Chile",
  "cn": "China",
  "co": "Colombia",
  "cr": "Costa Rica",
  "hr": "Croatia",
  "cu": "Cuba",
  "cw": "Curaçao",
  "cy": "Cyprus",
  "cz": "Czech Republic",
  "dk": "Denmark",
  "do": "Dominican Republic",
  "ec": "Ecuador",
  "eg": "Egypt",
  "sv": "El Salvador",
  "ee": "Estonia",
  "et": "Ethiopia",
  "fi": "Finland",
  "fr": "France",
  "ge": "Georgia",
  "de": "Germany",
  "gh": "Ghana",
  "gr": "Greece",
  "gt": "Guatemala",
  "hk": "Hong Kong",
  "hn": "Honduras",
  "hu": "Hungary",
  "is": "Iceland",
  "in": "India",
  "id": "Indonesia",
  "ir": "Iran",
  "iq": "Iraq",
  "ie": "Ireland",
  "il": "Israel",
  "it": "Italy",
  "jm": "Jamaica",
  "jp": "Japan",
  "jo": "Jordan",
  "kz": "Kazakhstan",
  "ke": "Kenya",
  "xk": "Kosovo",
  "kw": "Kuwait",
  "kg": "Kyrgyzstan",
  "la": "Laos",
  "lv": "Latvia",
  "lb": "Lebanon",
  "ly": "Libya",
  "lt": "Lithuania",
  "lu": "Luxembourg",
  "mo": "Macao",
  "mk": "North Macedonia",
  "my": "Malaysia",
  "mt": "Malta",
  "mx": "Mexico",
  "md": "Moldova",
  "mn": "Mongolia",
  "me": "Montenegro",
  "ma": "Morocco",
  "mz": "Mozambique",
  "mm": "Myanmar",
  "np": "Nepal",
  "nl": "Netherlands",
  "nz": "New Zealand",
  "ni": "Nicaragua",
  "ng": "Nigeria",
  "no": "Norway",
  "om": "Oman",
  "pk": "Pakistan",
  "pa": "Panama",
  "py": "Paraguay",
  "pe": "Peru",
  "ph": "Philippines",
  "pl": "Poland",
  "pt": "Portugal",
  "pr": "Puerto Rico",
  "qa": "Qatar",
  "ro": "Romania",
  "ru": "Russia",
  "rw": "Rwanda",
  "sa": "Saudi Arabia",
  "sn": "Senegal",
  "rs": "Serbia",
  "sg": "Singapore",
  "sk": "Slovakia",
  "si": "Slovenia",
  "za": "South Africa",
  "kr": "South Korea",
  "es": "Spain",
  "lk": "Sri Lanka",
  "sd": "Sudan",
  "se": "Sweden",
  "ch": "Switzerland",
  "sy": "Syria",
  "tw": "Taiwan",
  "tj": "Tajikistan",
  "tz": "Tanzania",
  "th": "Thailand",
  "tn": "Tunisia",
  "tr": "Turkey",
  "tm": "Turkmenistan",
  "ug": "Uganda",
  "ua": "Ukraine",
  "ae": "United Arab Emirates",
  "gb": "United Kingdom",
  "uy": "Uruguay",
  "uz": "Uzbekistan",
  "ve": "Venezuela",
  "vn": "Vietnam",
  "ye": "Yemen",
  "zm": "Zambia",
  "zw": "Zimbabwe",

  // === ISO 3166-1 alpha-3 codes ===
  "arg": "Argentina",
  "are": "United Arab Emirates",
  "aus": "Australia",
  "aut": "Austria",
  "bel": "Belgium",
  "bgd": "Bangladesh",
  "bgr": "Bulgaria",
  "bra": "Brazil",
  "can": "Canada",
  "che": "Switzerland",
  "chn": "China",
  "col": "Colombia",
  "cze": "Czech Republic",
  "deu": "Germany",
  "dnk": "Denmark",
  "egy": "Egypt",
  "esp": "Spain",
  "fin": "Finland",
  "fra": "France",
  "gbr": "United Kingdom",
  "hkg": "Hong Kong",
  "hrv": "Croatia",
  "hun": "Hungary",
  "idn": "Indonesia",
  "ind": "India",
  "irn": "Iran",
  "irq": "Iraq",
  "isl": "Iceland",
  "isr": "Israel",
  "ita": "Italy",
  "jpn": "Japan",
  "kaz": "Kazakhstan",
  "ken": "Kenya",
  "kor": "South Korea",
  "lka": "Sri Lanka",
  "mar": "Morocco",
  "mys": "Malaysia",
  "nga": "Nigeria",
  "nic": "Nicaragua",
  "nld": "Netherlands",
  "nor": "Norway",
  "npl": "Nepal",
  "nzl": "New Zealand",
  "pak": "Pakistan",
  "per": "Peru",
  "phl": "Philippines",
  "pol": "Poland",
  "prt": "Portugal",
  "qat": "Qatar",
  "roc": "Taiwan",
  "rou": "Romania",
  "rus": "Russia",
  "sau": "Saudi Arabia",
  "sgp": "Singapore",
  "srb": "Serbia",
  "svk": "Slovakia",
  "svn": "Slovenia",
  "swe": "Sweden",
  "tha": "Thailand",
  "tur": "Turkey",
  "twn": "Taiwan",
  "ukr": "Ukraine",
  "vnm": "Vietnam",
  "zaf": "South Africa",

  // === Local language names ===
  "maroc": "Morocco",
  "belgique": "Belgium",
  "viet nam": "Vietnam",
  "cod": "Democratic Republic of the Congo",
  "dom": "Dominican Republic",
  "algérie": "Algeria",
  "côte d'ivoire": "Ivory Coast",
  "suisse": "Switzerland",
  "deutschland": "Germany",
  "méxico": "Mexico",
  "perú": "Peru",
  "italia": "Italy",
  "españa": "Spain",
  "schweiz": "Switzerland",
  "österreich": "Austria",
  "nederland": "Netherlands",
  "sverige": "Sweden",
  "norge": "Norway",
  "danmark": "Denmark",
  "suomi": "Finland",
  "ísland": "Iceland",
  "polska": "Poland",
  "česko": "Czech Republic",
  "magyarország": "Hungary",
  "românia": "Romania",
  "hrvatska": "Croatia",
  "србија": "Serbia",
  "slovenija": "Slovenia",
  "slovensko": "Slovakia",
  "україна": "Ukraine",
  "россия": "Russia",
  "日本": "Japan",
  "中国": "China",
  "한국": "South Korea",
  "中華民國": "Taiwan",
  "hawai'i": "United States",

  // === Identity mappings ===
  "denmark": "Denmark",
  "france": "France",
  "italy": "Italy",
  "japan": "Japan",
  "spain": "Spain",
  "sweden": "Sweden",
  "norway": "Norway",
  "finland": "Finland",
  "australia": "Australia",
  "canada": "Canada",
  "brazil": "Brazil",
  "brasil": "Brazil",
  "india": "India",
  "israel": "Israel",
  "turkey": "Turkey",
  "türkiye": "Turkey",
  "turkiye": "Turkey",
  "egypt": "Egypt",
  "saudi arabia": "Saudi Arabia",
  "kingdom of saudi arabia": "Saudi Arabia",
  "iran": "Iran",
  "iraq": "Iraq",
  "pakistan": "Pakistan",
  "south africa": "South Africa",
  "nigeria": "Nigeria",
  "argentina": "Argentina",
  "mexico": "Mexico",
  "mex": "Mexico",
  "colombia": "Colombia",
  "chile": "Chile",
  "taiwan": "Taiwan",
  "r.o.c": "Taiwan",   // Republic of China — lookupCountry strips trailing dot before lookup
  "taiwan, roc": "Taiwan",
  "iran (the islamic republic of)": "Iran",
  "singapore": "Singapore",
  "hong kong": "Hong Kong",
  "thailand": "Thailand",
  "indonesia": "Indonesia",
  "malaysia": "Malaysia",
  "philippines": "Philippines",
  "vietnam": "Vietnam",
  "new zealand": "New Zealand",
  "new caledonia": "New Caledonia",
  "greenland": "Greenland",
  "ireland": "Ireland",
  "belgium": "Belgium",
  "switzerland": "Switzerland",
  "austria": "Austria",
  "poland": "Poland",
  "portugal": "Portugal",
  "greece": "Greece",
  "hungary": "Hungary",
  "romania": "Romania",
  "croatia": "Croatia",
  "serbia": "Serbia",
  "bulgaria": "Bulgaria",
  "slovakia": "Slovakia",
  "slovenia": "Slovenia",
  "estonia": "Estonia",
  "latvia": "Latvia",
  "lithuania": "Lithuania",
  "ukraine": "Ukraine",
  "georgia": "Georgia",
  "kazakhstan": "Kazakhstan",
  "uzbekistan": "Uzbekistan",
  "peru": "Peru",
  "venezuela": "Venezuela",
  "ecuador": "Ecuador",
  "uruguay": "Uruguay",
  "paraguay": "Paraguay",
  "bolivia": "Bolivia",
  "cuba": "Cuba",
  "dominican republic": "Dominican Republic",
  "jamaica": "Jamaica",
  "costa rica": "Costa Rica",
  "panama": "Panama",
  "guatemala": "Guatemala",
  "honduras": "Honduras",
  "el salvador": "El Salvador",
  "nicaragua": "Nicaragua",
  "puerto rico": "Puerto Rico",
  "morocco": "Morocco",
  "tunisia": "Tunisia",
  "algeria": "Algeria",
  "libya": "Libya",
  "kenya": "Kenya",
  "ethiopia": "Ethiopia",
  "ghana": "Ghana",
  "tanzania": "Tanzania",
  "uganda": "Uganda",
  "mozambique": "Mozambique",
  "cameroon": "Cameroon",
  "senegal": "Senegal",
  "ivory coast": "Ivory Coast",
  "lebanon": "Lebanon",
  "jordan": "Jordan",
  "syria": "Syria",
  "yemen": "Yemen",
  "oman": "Oman",
  "qatar": "Qatar",
  "bahrain": "Bahrain",
  "kuwait": "Kuwait",
  "united arab emirates": "United Arab Emirates",
  "uae": "United Arab Emirates",
  "afghanistan": "Afghanistan",
  "bangladesh": "Bangladesh",
  "sri lanka": "Sri Lanka",
  "nepal": "Nepal",
  "myanmar": "Myanmar",
  "cambodia": "Cambodia",
  "laos": "Laos",
  "mongolia": "Mongolia",
  "north korea": "North Korea",
  "cyprus": "Cyprus",
  "malta": "Malta",
  "luxembourg": "Luxembourg",
  "iceland": "Iceland",
  "albania": "Albania",
  "montenegro": "Montenegro",
  "bosnia and herzegovina": "Bosnia and Herzegovina",
  "kosovo": "Kosovo",
  "moldova": "Moldova",
  "belarus": "Belarus",
  "armenia": "Armenia",
  "azerbaijan": "Azerbaijan",
  "turkmenistan": "Turkmenistan",
  "tajikistan": "Tajikistan",
  "kyrgyzstan": "Kyrgyzstan",
  "curaçao": "Curaçao",
  "curacao": "Curaçao",

  // US state full names → "United States"
  "texas": "United States",
  "california": "United States",
  "new york": "United States",
  "florida": "United States",
  "illinois": "United States",
  "pennsylvania": "United States",
  "ohio": "United States",
  "michigan": "United States",
  "massachusetts": "United States",
  "minnesota": "United States",
  "maryland": "United States",
  "virginia": "United States",
  "connecticut": "United States",
  "oklahoma": "United States",
  "wisconsin": "United States",
  "colorado": "United States",
  "oregon": "United States",
  "washington": "United States",
  "tennessee": "United States",
  "indiana": "United States",
  "missouri": "United States",
  "arizona": "United States",
  "north carolina": "United States",
  "south carolina": "United States",
  "alabama": "United States",
  "louisiana": "United States",
  "kentucky": "United States",
  "iowa": "United States",
  "utah": "United States",
  "nebraska": "United States",
  "kansas": "United States",
  "nevada": "United States",
  "new jersey": "United States",
  "new hampshire": "United States",
  "new mexico": "United States",
  "hawaii": "United States",
  "maine": "United States",
  "vermont": "United States",
  "rhode island": "United States",
  "delaware": "United States",
  "montana": "United States",
  "idaho": "United States",
  "wyoming": "United States",
  "west virginia": "United States",
  "arkansas": "United States",
  "mississippi": "United States",
  "north dakota": "United States",
  "south dakota": "United States",
  "alaska": "United States",
  "district of columbia": "United States",
};

/** Case-insensitive country lookup. Handles trailing dots/whitespace. */
export function lookupCountry(raw: string): string | null {
  const cleaned = raw.replace(/\.+$/, "").trim().toLowerCase();
  return RAW_COUNTRY_MAP[cleaned] ?? null;
}

/** All canonical country names (unique values) for substring matching */
export const CANONICAL_COUNTRIES: string[] = [...new Set(Object.values(RAW_COUNTRY_MAP))];

// ── Country → region / continent ──────────────────────────────────────────────
// continent-map.ts covers ~190 countries. A handful of canonical names used in
// this file (Hong Kong, Macao, Taiwan, Puerto Rico, Curaçao) are not in that map.
// We patch them here so all names reachable via lookupCountry have full coverage.

import {
  getRegion as _getRegionBase,
  getContinent as _getContinentFromRegion,
} from "./continent-map";

const EXTRA_COUNTRY_REGION: Record<string, string> = {
  "hong kong":      "East Asia",
  "macao":          "East Asia",
  "taiwan":         "East Asia",
  "puerto rico":    "Central America & Caribbean",
  "curaçao":        "Central America & Caribbean",
  "new caledonia":  "Oceania",
  "greenland":      "North America",
};

/**
 * Maps a canonical country name to its UN region.
 * Case-insensitive. Covers all names reachable via lookupCountry().
 * Returns null for unknown countries.
 */
export function getRegion(country: string): string | null {
  const key = country.trim().toLowerCase();
  return EXTRA_COUNTRY_REGION[key] ?? _getRegionBase(key) ?? null;
}

/**
 * Maps a canonical country name directly to its continent.
 * Case-insensitive. Returns null for unknown countries.
 * (Distinct from continent-map.getContinent which takes a region name.)
 */
export function getContinent(country: string): string | null {
  const region = getRegion(country);
  return region ? _getContinentFromRegion(region) : null;
}

/** US state abbreviations → full name */
export const US_STATES: Record<string, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District of Columbia",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  // Full state names (uppercase) — for lookups like "Georgia", "Virginia"
  ALABAMA: "Alabama",
  ALASKA: "Alaska",
  ARIZONA: "Arizona",
  ARKANSAS: "Arkansas",
  CALIFORNIA: "California",
  COLORADO: "Colorado",
  CONNECTICUT: "Connecticut",
  DELAWARE: "Delaware",
  "DISTRICT OF COLUMBIA": "District of Columbia",
  FLORIDA: "Florida",
  GEORGIA: "Georgia",
  HAWAII: "Hawaii",
  IDAHO: "Idaho",
  ILLINOIS: "Illinois",
  INDIANA: "Indiana",
  IOWA: "Iowa",
  KANSAS: "Kansas",
  KENTUCKY: "Kentucky",
  LOUISIANA: "Louisiana",
  MAINE: "Maine",
  MARYLAND: "Maryland",
  MASSACHUSETTS: "Massachusetts",
  MICHIGAN: "Michigan",
  MINNESOTA: "Minnesota",
  MISSISSIPPI: "Mississippi",
  MISSOURI: "Missouri",
  MONTANA: "Montana",
  NEBRASKA: "Nebraska",
  NEVADA: "Nevada",
  "NEW HAMPSHIRE": "New Hampshire",
  "NEW JERSEY": "New Jersey",
  "NEW MEXICO": "New Mexico",
  "NEW YORK": "New York",
  "NORTH CAROLINA": "North Carolina",
  "NORTH DAKOTA": "North Dakota",
  OHIO: "Ohio",
  OKLAHOMA: "Oklahoma",
  OREGON: "Oregon",
  PENNSYLVANIA: "Pennsylvania",
  "PUERTO RICO": "Puerto Rico",
  "RHODE ISLAND": "Rhode Island",
  "SOUTH CAROLINA": "South Carolina",
  "SOUTH DAKOTA": "South Dakota",
  TENNESSEE: "Tennessee",
  TEXAS: "Texas",
  UTAH: "Utah",
  VERMONT: "Vermont",
  VIRGINIA: "Virginia",
  WASHINGTON: "Washington",
  "WEST VIRGINIA": "West Virginia",
  WISCONSIN: "Wisconsin",
  WYOMING: "Wyoming",
};
