/**
 * City-to-country fallback for affiliations that end with a city
 * instead of a country. Case-insensitive lookup.
 */

export interface CityInfo {
  city: string;
  country: string;
}

export const CITY_TO_COUNTRY: Record<string, CityInfo> = {
  // === United States ===
  "ann arbor": { city: "Ann Arbor", country: "United States" },
  "atlanta": { city: "Atlanta", country: "United States" },
  "baltimore": { city: "Baltimore", country: "United States" },
  "boston": { city: "Boston", country: "United States" },
  "bronx": { city: "Bronx", country: "United States" },
  "buffalo": { city: "Buffalo", country: "United States" },
  "carmel": { city: "Carmel", country: "United States" },
  "charlottesville": { city: "Charlottesville", country: "United States" },
  "chicago": { city: "Chicago", country: "United States" },
  "cincinnati": { city: "Cincinnati", country: "United States" },
  "cleveland": { city: "Cleveland", country: "United States" },
  "dallas": { city: "Dallas", country: "United States" },
  "denver": { city: "Denver", country: "United States" },
  "detroit": { city: "Detroit", country: "United States" },
  "el paso": { city: "El Paso", country: "United States" },
  "gainesville": { city: "Gainesville", country: "United States" },
  "houston": { city: "Houston", country: "United States" },
  "indianapolis": { city: "Indianapolis", country: "United States" },
  "la jolla": { city: "La Jolla", country: "United States" },
  "los angeles": { city: "Los Angeles", country: "United States" },
  "louisville": { city: "Louisville", country: "United States" },
  "memphis": { city: "Memphis", country: "United States" },
  "miami": { city: "Miami", country: "United States" },
  "milwaukee": { city: "Milwaukee", country: "United States" },
  "minneapolis": { city: "Minneapolis", country: "United States" },
  "nashville": { city: "Nashville", country: "United States" },
  "new haven": { city: "New Haven", country: "United States" },
  "new york": { city: "New York", country: "United States" },
  "philadelphia": { city: "Philadelphia", country: "United States" },
  "pittsburgh": { city: "Pittsburgh", country: "United States" },
  "portland": { city: "Portland", country: "United States" },
  "providence": { city: "Providence", country: "United States" },
  "rochester": { city: "Rochester", country: "United States" },
  "salt lake city": { city: "Salt Lake City", country: "United States" },
  "san diego": { city: "San Diego", country: "United States" },
  "san francisco": { city: "San Francisco", country: "United States" },
  "seattle": { city: "Seattle", country: "United States" },
  "stanford": { city: "Stanford", country: "United States" },
  "tampa": { city: "Tampa", country: "United States" },

  // === China — cities ===
  "beijing": { city: "Beijing", country: "China" },
  "changchun": { city: "Changchun", country: "China" },
  "changsha": { city: "Changsha", country: "China" },
  "chengdu": { city: "Chengdu", country: "China" },
  "chongqing": { city: "Chongqing", country: "China" },
  "fuzhou": { city: "Fuzhou", country: "China" },
  "guangzhou": { city: "Guangzhou", country: "China" },
  "hangzhou": { city: "Hangzhou", country: "China" },
  "harbin": { city: "Harbin", country: "China" },
  "hefei": { city: "Hefei", country: "China" },
  "jinan": { city: "Jinan", country: "China" },
  "kunming": { city: "Kunming", country: "China" },
  "nanchang": { city: "Nanchang", country: "China" },
  "nanjing": { city: "Nanjing", country: "China" },
  "shanghai": { city: "Shanghai", country: "China" },
  "shenzhen": { city: "Shenzhen", country: "China" },
  "tianjin": { city: "Tianjin", country: "China" },
  "wuhan": { city: "Wuhan", country: "China" },
  "xi'an": { city: "Xi'an", country: "China" },
  "zhengzhou": { city: "Zhengzhou", country: "China" },

  // === China — provinces ===
  "anhui": { city: "Hefei", country: "China" },
  "fujian": { city: "Fuzhou", country: "China" },
  "gansu": { city: "Lanzhou", country: "China" },
  "guangdong": { city: "Guangzhou", country: "China" },
  "guizhou": { city: "Guiyang", country: "China" },
  "hebei": { city: "Shijiazhuang", country: "China" },
  "heilongjiang": { city: "Harbin", country: "China" },
  "henan": { city: "Zhengzhou", country: "China" },
  "hubei": { city: "Wuhan", country: "China" },
  "hunan": { city: "Changsha", country: "China" },
  "jiangsu": { city: "Nanjing", country: "China" },
  "jiangsu province": { city: "Nanjing", country: "China" },
  "jilin": { city: "Changchun", country: "China" },
  "liaoning": { city: "Shenyang", country: "China" },
  "shaanxi": { city: "Xi'an", country: "China" },
  "shandong": { city: "Jinan", country: "China" },
  "shanxi": { city: "Taiyuan", country: "China" },
  "sichuan": { city: "Chengdu", country: "China" },
  "yunnan": { city: "Kunming", country: "China" },
  "zhejiang": { city: "Hangzhou", country: "China" },
  "zhejiang province": { city: "Hangzhou", country: "China" },

  // === Japan — cities ===
  "fukuoka": { city: "Fukuoka", country: "Japan" },
  "hiroshima": { city: "Hiroshima", country: "Japan" },
  "kobe": { city: "Kobe", country: "Japan" },
  "kyoto": { city: "Kyoto", country: "Japan" },
  "nagoya": { city: "Nagoya", country: "Japan" },
  "niigata": { city: "Niigata", country: "Japan" },
  "osaka": { city: "Osaka", country: "Japan" },
  "sapporo": { city: "Sapporo", country: "Japan" },
  "sendai": { city: "Sendai", country: "Japan" },
  "tokyo": { city: "Tokyo", country: "Japan" },

  // === Japan — prefectures ===
  "aichi": { city: "Nagoya", country: "Japan" },
  "chiba": { city: "Chiba", country: "Japan" },
  "fukushima": { city: "Fukushima", country: "Japan" },
  "gunma": { city: "Maebashi", country: "Japan" },
  "hokkaido": { city: "Sapporo", country: "Japan" },
  "hyogo": { city: "Kobe", country: "Japan" },
  "ibaraki": { city: "Mito", country: "Japan" },
  "kanagawa": { city: "Yokohama", country: "Japan" },
  "miyagi": { city: "Sendai", country: "Japan" },
  "nagano": { city: "Nagano", country: "Japan" },
  "saitama": { city: "Saitama", country: "Japan" },
  "shizuoka": { city: "Shizuoka", country: "Japan" },
  "tochigi": { city: "Utsunomiya", country: "Japan" },

  // === South Korea ===
  "busan": { city: "Busan", country: "South Korea" },
  "daegu": { city: "Daegu", country: "South Korea" },
  "gyeonggi": { city: "Suwon", country: "South Korea" },
  "gyeonggi-do": { city: "Suwon", country: "South Korea" },
  "incheon": { city: "Incheon", country: "South Korea" },
  "seongnam": { city: "Seongnam", country: "South Korea" },
  "seoul": { city: "Seoul", country: "South Korea" },

  // === Taiwan ===
  "taipei": { city: "Taipei", country: "Taiwan" },

  // === Canada — cities ===
  "montreal": { city: "Montreal", country: "Canada" },
  "ottawa": { city: "Ottawa", country: "Canada" },
  "toronto": { city: "Toronto", country: "Canada" },
  "vancouver": { city: "Vancouver", country: "Canada" },

  // === Canada — provinces ===
  "alberta": { city: "Edmonton", country: "Canada" },
  "british columbia": { city: "Vancouver", country: "Canada" },
  "ontario": { city: "Toronto", country: "Canada" },
  "quebec": { city: "Montreal", country: "Canada" },

  // === Scandinavia ===
  "copenhagen": { city: "Copenhagen", country: "Denmark" },
  "københavn": { city: "Copenhagen", country: "Denmark" },
  "kobenhavn": { city: "Copenhagen", country: "Denmark" },
  "aarhus": { city: "Aarhus", country: "Denmark" },
  "arhus": { city: "Aarhus", country: "Denmark" },
  "odense": { city: "Odense", country: "Denmark" },
  "aalborg": { city: "Aalborg", country: "Denmark" },
  "stockholm": { city: "Stockholm", country: "Sweden" },
  "gothenburg": { city: "Gothenburg", country: "Sweden" },
  "göteborg": { city: "Gothenburg", country: "Sweden" },
  "goteborg": { city: "Gothenburg", country: "Sweden" },
  "malmö": { city: "Malmö", country: "Sweden" },
  "malmo": { city: "Malmö", country: "Sweden" },
  "umeå": { city: "Umeå", country: "Sweden" },
  "umea": { city: "Umeå", country: "Sweden" },
  "linköping": { city: "Linköping", country: "Sweden" },
  "linkoping": { city: "Linköping", country: "Sweden" },
  "oslo": { city: "Oslo", country: "Norway" },
  "bergen": { city: "Bergen", country: "Norway" },
  "trondheim": { city: "Trondheim", country: "Norway" },
  "helsinki": { city: "Helsinki", country: "Finland" },
  "helsingfors": { city: "Helsinki", country: "Finland" },
  "tampere": { city: "Tampere", country: "Finland" },
  "turku": { city: "Turku", country: "Finland" },
  "åbo": { city: "Turku", country: "Finland" },
  "reykjavik": { city: "Reykjavik", country: "Iceland" },
  "reykjavík": { city: "Reykjavik", country: "Iceland" },

  // === United Kingdom ===
  "london": { city: "London", country: "United Kingdom" },
  "oxford": { city: "Oxford", country: "United Kingdom" },
  "cambridge": { city: "Cambridge", country: "United Kingdom" },
  "manchester": { city: "Manchester", country: "United Kingdom" },
  "birmingham": { city: "Birmingham", country: "United Kingdom" },
  "edinburgh": { city: "Edinburgh", country: "United Kingdom" },
  "glasgow": { city: "Glasgow", country: "United Kingdom" },
  "leeds": { city: "Leeds", country: "United Kingdom" },
  "sheffield": { city: "Sheffield", country: "United Kingdom" },
  "bristol": { city: "Bristol", country: "United Kingdom" },
  "newcastle": { city: "Newcastle", country: "United Kingdom" },
  "cardiff": { city: "Cardiff", country: "United Kingdom" },
  "belfast": { city: "Belfast", country: "United Kingdom" },
  "nottingham": { city: "Nottingham", country: "United Kingdom" },
  "liverpool": { city: "Liverpool", country: "United Kingdom" },

  // === France ===
  "paris": { city: "Paris", country: "France" },
  "lyon": { city: "Lyon", country: "France" },
  "marseille": { city: "Marseille", country: "France" },
  "toulouse": { city: "Toulouse", country: "France" },
  "bordeaux": { city: "Bordeaux", country: "France" },
  "lille": { city: "Lille", country: "France" },
  "strasbourg": { city: "Strasbourg", country: "France" },
  "nantes": { city: "Nantes", country: "France" },
  "montpellier": { city: "Montpellier", country: "France" },
  "rennes": { city: "Rennes", country: "France" },
  "grenoble": { city: "Grenoble", country: "France" },
  "nice": { city: "Nice", country: "France" },

  // === Germany ===
  "berlin": { city: "Berlin", country: "Germany" },
  "munich": { city: "Munich", country: "Germany" },
  "münchen": { city: "Munich", country: "Germany" },
  "munchen": { city: "Munich", country: "Germany" },
  "hamburg": { city: "Hamburg", country: "Germany" },
  "cologne": { city: "Cologne", country: "Germany" },
  "köln": { city: "Cologne", country: "Germany" },
  "koln": { city: "Cologne", country: "Germany" },
  "frankfurt": { city: "Frankfurt", country: "Germany" },
  "stuttgart": { city: "Stuttgart", country: "Germany" },
  "düsseldorf": { city: "Düsseldorf", country: "Germany" },
  "dusseldorf": { city: "Düsseldorf", country: "Germany" },
  "heidelberg": { city: "Heidelberg", country: "Germany" },
  "tübingen": { city: "Tübingen", country: "Germany" },
  "tuebingen": { city: "Tübingen", country: "Germany" },
  "hannover": { city: "Hannover", country: "Germany" },
  "hanover": { city: "Hannover", country: "Germany" },
  "göttingen": { city: "Göttingen", country: "Germany" },
  "gottingen": { city: "Göttingen", country: "Germany" },
  "freiburg": { city: "Freiburg", country: "Germany" },
  "bonn": { city: "Bonn", country: "Germany" },
  "aachen": { city: "Aachen", country: "Germany" },
  "münster": { city: "Münster", country: "Germany" },
  "munster": { city: "Münster", country: "Germany" },
  "dresden": { city: "Dresden", country: "Germany" },
  "leipzig": { city: "Leipzig", country: "Germany" },
  "kiel": { city: "Kiel", country: "Germany" },
  "mainz": { city: "Mainz", country: "Germany" },
  "erlangen": { city: "Erlangen", country: "Germany" },
  "würzburg": { city: "Würzburg", country: "Germany" },
  "wurzburg": { city: "Würzburg", country: "Germany" },
  "regensburg": { city: "Regensburg", country: "Germany" },
  "ulm": { city: "Ulm", country: "Germany" },
  "marburg": { city: "Marburg", country: "Germany" },
  "giessen": { city: "Giessen", country: "Germany" },
  "gießen": { city: "Giessen", country: "Germany" },

  // === Italy ===
  "rome": { city: "Rome", country: "Italy" },
  "roma": { city: "Rome", country: "Italy" },
  "milan": { city: "Milan", country: "Italy" },
  "milano": { city: "Milan", country: "Italy" },
  "naples": { city: "Naples", country: "Italy" },
  "napoli": { city: "Naples", country: "Italy" },
  "turin": { city: "Turin", country: "Italy" },
  "torino": { city: "Turin", country: "Italy" },
  "florence": { city: "Florence", country: "Italy" },
  "firenze": { city: "Florence", country: "Italy" },
  "bologna": { city: "Bologna", country: "Italy" },
  "padua": { city: "Padua", country: "Italy" },
  "padova": { city: "Padua", country: "Italy" },
  "venice": { city: "Venice", country: "Italy" },
  "venezia": { city: "Venice", country: "Italy" },
  "genoa": { city: "Genoa", country: "Italy" },
  "genova": { city: "Genoa", country: "Italy" },
  "palermo": { city: "Palermo", country: "Italy" },
  "pisa": { city: "Pisa", country: "Italy" },
  "verona": { city: "Verona", country: "Italy" },
  "bari": { city: "Bari", country: "Italy" },
  "pavia": { city: "Pavia", country: "Italy" },
  "modena": { city: "Modena", country: "Italy" },
  "parma": { city: "Parma", country: "Italy" },
  "perugia": { city: "Perugia", country: "Italy" },
  "trieste": { city: "Trieste", country: "Italy" },
  "siena": { city: "Siena", country: "Italy" },
  "catania": { city: "Catania", country: "Italy" },
  "messina": { city: "Messina", country: "Italy" },
  "cagliari": { city: "Cagliari", country: "Italy" },

  // === Spain ===
  "madrid": { city: "Madrid", country: "Spain" },
  "barcelona": { city: "Barcelona", country: "Spain" },
  "valencia": { city: "Valencia", country: "Spain" },
  "seville": { city: "Seville", country: "Spain" },
  "sevilla": { city: "Seville", country: "Spain" },
  "granada": { city: "Granada", country: "Spain" },
  "bilbao": { city: "Bilbao", country: "Spain" },
  "zaragoza": { city: "Zaragoza", country: "Spain" },
  "málaga": { city: "Málaga", country: "Spain" },
  "malaga": { city: "Málaga", country: "Spain" },
  "salamanca": { city: "Salamanca", country: "Spain" },
  "santiago de compostela": { city: "Santiago de Compostela", country: "Spain" },
  "pamplona": { city: "Pamplona", country: "Spain" },
  "oviedo": { city: "Oviedo", country: "Spain" },
  "valladolid": { city: "Valladolid", country: "Spain" },

  // === Netherlands ===
  "amsterdam": { city: "Amsterdam", country: "Netherlands" },
  "rotterdam": { city: "Rotterdam", country: "Netherlands" },
  "utrecht": { city: "Utrecht", country: "Netherlands" },
  "leiden": { city: "Leiden", country: "Netherlands" },
  "groningen": { city: "Groningen", country: "Netherlands" },
  "nijmegen": { city: "Nijmegen", country: "Netherlands" },
  "maastricht": { city: "Maastricht", country: "Netherlands" },
  "eindhoven": { city: "Eindhoven", country: "Netherlands" },
  "the hague": { city: "The Hague", country: "Netherlands" },
  "den haag": { city: "The Hague", country: "Netherlands" },
  "'s-gravenhage": { city: "The Hague", country: "Netherlands" },

  // === Switzerland ===
  "zurich": { city: "Zurich", country: "Switzerland" },
  "zürich": { city: "Zurich", country: "Switzerland" },
  "zuerich": { city: "Zurich", country: "Switzerland" },
  "bern": { city: "Bern", country: "Switzerland" },
  "berne": { city: "Bern", country: "Switzerland" },
  "lausanne": { city: "Lausanne", country: "Switzerland" },
  "geneva": { city: "Geneva", country: "Switzerland" },
  "genève": { city: "Geneva", country: "Switzerland" },
  "geneve": { city: "Geneva", country: "Switzerland" },
  "basel": { city: "Basel", country: "Switzerland" },
  "basle": { city: "Basel", country: "Switzerland" },

  // === Belgium ===
  "brussels": { city: "Brussels", country: "Belgium" },
  "bruxelles": { city: "Brussels", country: "Belgium" },
  "brussel": { city: "Brussels", country: "Belgium" },
  "ghent": { city: "Ghent", country: "Belgium" },
  "gent": { city: "Ghent", country: "Belgium" },
  "leuven": { city: "Leuven", country: "Belgium" },
  "louvain": { city: "Leuven", country: "Belgium" },
  "liege": { city: "Liège", country: "Belgium" },
  "liège": { city: "Liège", country: "Belgium" },
  "antwerp": { city: "Antwerp", country: "Belgium" },
  "antwerpen": { city: "Antwerp", country: "Belgium" },

  // === Austria ===
  "vienna": { city: "Vienna", country: "Austria" },
  "wien": { city: "Vienna", country: "Austria" },
  "graz": { city: "Graz", country: "Austria" },
  "innsbruck": { city: "Innsbruck", country: "Austria" },
  "salzburg": { city: "Salzburg", country: "Austria" },

  // === Poland ===
  "warsaw": { city: "Warsaw", country: "Poland" },
  "warszawa": { city: "Warsaw", country: "Poland" },
  "krakow": { city: "Krakow", country: "Poland" },
  "kraków": { city: "Krakow", country: "Poland" },
  "wroclaw": { city: "Wroclaw", country: "Poland" },
  "wrocław": { city: "Wroclaw", country: "Poland" },
  "poznan": { city: "Poznan", country: "Poland" },
  "poznań": { city: "Poznan", country: "Poland" },
  "gdansk": { city: "Gdansk", country: "Poland" },
  "gdańsk": { city: "Gdansk", country: "Poland" },
  "lodz": { city: "Lodz", country: "Poland" },
  "łódź": { city: "Lodz", country: "Poland" },

  // === Czech Republic ===
  "prague": { city: "Prague", country: "Czech Republic" },
  "praha": { city: "Prague", country: "Czech Republic" },
  "brno": { city: "Brno", country: "Czech Republic" },

  // === Other Europe ===
  "lisbon": { city: "Lisbon", country: "Portugal" },
  "lisboa": { city: "Lisbon", country: "Portugal" },
  "porto": { city: "Porto", country: "Portugal" },
  "athens": { city: "Athens", country: "Greece" },
  "athina": { city: "Athens", country: "Greece" },
  "thessaloniki": { city: "Thessaloniki", country: "Greece" },
  "budapest": { city: "Budapest", country: "Hungary" },
  "bucharest": { city: "Bucharest", country: "Romania" },
  "bucuresti": { city: "Bucharest", country: "Romania" },
  "sofia": { city: "Sofia", country: "Bulgaria" },
  "zagreb": { city: "Zagreb", country: "Croatia" },
  "belgrade": { city: "Belgrade", country: "Serbia" },
  "beograd": { city: "Belgrade", country: "Serbia" },
  "bratislava": { city: "Bratislava", country: "Slovakia" },
  "vilnius": { city: "Vilnius", country: "Lithuania" },
  "riga": { city: "Riga", country: "Latvia" },
  "tallinn": { city: "Tallinn", country: "Estonia" },
  "moscow": { city: "Moscow", country: "Russia" },
  "moskva": { city: "Moscow", country: "Russia" },
  "saint petersburg": { city: "Saint Petersburg", country: "Russia" },
  "st. petersburg": { city: "Saint Petersburg", country: "Russia" },
  "st petersburg": { city: "Saint Petersburg", country: "Russia" },

  // === Middle East ===
  "tehran": { city: "Tehran", country: "Iran" },
  "istanbul": { city: "Istanbul", country: "Turkey" },
  "ankara": { city: "Ankara", country: "Turkey" },
  "riyadh": { city: "Riyadh", country: "Saudi Arabia" },
  "dubai": { city: "Dubai", country: "United Arab Emirates" },
  "abu dhabi": { city: "Abu Dhabi", country: "United Arab Emirates" },
  "beirut": { city: "Beirut", country: "Lebanon" },
  "amman": { city: "Amman", country: "Jordan" },
  "tel aviv": { city: "Tel Aviv", country: "Israel" },
  "jerusalem": { city: "Jerusalem", country: "Israel" },
  "doha": { city: "Doha", country: "Qatar" },
  "kuwait city": { city: "Kuwait City", country: "Kuwait" },
  "baghdad": { city: "Baghdad", country: "Iraq" },
  "muscat": { city: "Muscat", country: "Oman" },

  // === Africa ===
  "cairo": { city: "Cairo", country: "Egypt" },
  "al-qahirah": { city: "Cairo", country: "Egypt" },
  "alexandria": { city: "Alexandria", country: "Egypt" },
  "casablanca": { city: "Casablanca", country: "Morocco" },
  "rabat": { city: "Rabat", country: "Morocco" },
  "oujda": { city: "Oujda", country: "Morocco" },
  "tunis": { city: "Tunis", country: "Tunisia" },
  "algiers": { city: "Algiers", country: "Algeria" },
  "lagos": { city: "Lagos", country: "Nigeria" },
  "abuja": { city: "Abuja", country: "Nigeria" },
  "nairobi": { city: "Nairobi", country: "Kenya" },
  "johannesburg": { city: "Johannesburg", country: "South Africa" },
  "cape town": { city: "Cape Town", country: "South Africa" },
  "accra": { city: "Accra", country: "Ghana" },
  "dakar": { city: "Dakar", country: "Senegal" },
  "addis ababa": { city: "Addis Ababa", country: "Ethiopia" },
  "cotonou": { city: "Cotonou", country: "Benin" },
  "kinshasa": { city: "Kinshasa", country: "Democratic Republic of the Congo" },
  "khartoum": { city: "Khartoum", country: "Sudan" },

  // === South Asia ===
  "mumbai": { city: "Mumbai", country: "India" },
  "bombay": { city: "Mumbai", country: "India" },
  "delhi": { city: "Delhi", country: "India" },
  "new delhi": { city: "New Delhi", country: "India" },
  "bangalore": { city: "Bangalore", country: "India" },
  "bengaluru": { city: "Bangalore", country: "India" },
  "chennai": { city: "Chennai", country: "India" },
  "madras": { city: "Chennai", country: "India" },
  "kolkata": { city: "Kolkata", country: "India" },
  "calcutta": { city: "Kolkata", country: "India" },
  "hyderabad": { city: "Hyderabad", country: "India" },
  "pune": { city: "Pune", country: "India" },
  "ahmedabad": { city: "Ahmedabad", country: "India" },
  "chandigarh": { city: "Chandigarh", country: "India" },
  "vellore": { city: "Vellore", country: "India" },
  "karachi": { city: "Karachi", country: "Pakistan" },
  "lahore": { city: "Lahore", country: "Pakistan" },
  "islamabad": { city: "Islamabad", country: "Pakistan" },
  "dhaka": { city: "Dhaka", country: "Bangladesh" },
  "colombo": { city: "Colombo", country: "Sri Lanka" },
  "kathmandu": { city: "Kathmandu", country: "Nepal" },

  // === Southeast Asia ===
  "hanoi": { city: "Hanoi", country: "Vietnam" },
  "ho chi minh city": { city: "Ho Chi Minh City", country: "Vietnam" },
  "saigon": { city: "Ho Chi Minh City", country: "Vietnam" },
  "bangkok": { city: "Bangkok", country: "Thailand" },
  "krung thep": { city: "Bangkok", country: "Thailand" },
  "singapore": { city: "Singapore", country: "Singapore" },
  "jakarta": { city: "Jakarta", country: "Indonesia" },
  "kuala lumpur": { city: "Kuala Lumpur", country: "Malaysia" },
  "manila": { city: "Manila", country: "Philippines" },
  "yangon": { city: "Yangon", country: "Myanmar" },
  "rangoon": { city: "Yangon", country: "Myanmar" },
  "phnom penh": { city: "Phnom Penh", country: "Cambodia" },

  // === Latin America ===
  "são paulo": { city: "São Paulo", country: "Brazil" },
  "sao paulo": { city: "São Paulo", country: "Brazil" },
  "rio de janeiro": { city: "Rio de Janeiro", country: "Brazil" },
  "brasília": { city: "Brasília", country: "Brazil" },
  "brasilia": { city: "Brasília", country: "Brazil" },
  "belo horizonte": { city: "Belo Horizonte", country: "Brazil" },
  "porto alegre": { city: "Porto Alegre", country: "Brazil" },
  "buenos aires": { city: "Buenos Aires", country: "Argentina" },
  "santiago": { city: "Santiago", country: "Chile" },
  "bogotá": { city: "Bogotá", country: "Colombia" },
  "bogota": { city: "Bogotá", country: "Colombia" },
  "lima": { city: "Lima", country: "Peru" },
  "mexico city": { city: "Mexico City", country: "Mexico" },
  "ciudad de méxico": { city: "Mexico City", country: "Mexico" },
  "monterrey": { city: "Monterrey", country: "Mexico" },
  "guadalajara": { city: "Guadalajara", country: "Mexico" },

  // === Oceania ===
  "sydney": { city: "Sydney", country: "Australia" },
  "melbourne": { city: "Melbourne", country: "Australia" },
  "brisbane": { city: "Brisbane", country: "Australia" },
  "perth": { city: "Perth", country: "Australia" },
  "adelaide": { city: "Adelaide", country: "Australia" },
  "auckland": { city: "Auckland", country: "New Zealand" },
  "wellington": { city: "Wellington", country: "New Zealand" },
};

/** Case-insensitive city lookup. Returns city + country or null. */
export function lookupCity(raw: string): CityInfo | null {
  const cleaned = raw.replace(/\.+$/, "").trim().toLowerCase();
  return CITY_TO_COUNTRY[cleaned] ?? null;
}
