/**
 * Deterministic country-name normalizer and US state lookup.
 * No AI, no external APIs — pure mapping.
 */

// Canonical country names keyed by lowercased variant
const RAW_COUNTRY_MAP: Record<string, string> = {
  // === Aliases ===
  "usa": "United States",
  "us": "United States",
  "u.s.a.": "United States",
  "u.s.a": "United States",
  "u.s.": "United States",
  "united states": "United States",
  "united states of america": "United States",

  "uk": "United Kingdom",
  "u.k.": "United Kingdom",
  "u.k": "United Kingdom",
  "united kingdom": "United Kingdom",
  "england": "United Kingdom",
  "scotland": "United Kingdom",
  "wales": "United Kingdom",
  "northern ireland": "United Kingdom",

  "prc": "China",
  "p.r. china": "China",
  "p.r.china": "China",
  "pr china": "China",
  "people's republic of china": "China",
  "china": "China",

  "republic of korea": "South Korea",
  "south korea": "South Korea",
  "rok": "South Korea",

  "republic of north macedonia": "North Macedonia",
  "rn macedonia": "North Macedonia",
  "r. macedonia": "North Macedonia",
  "republic of macedonia": "North Macedonia",
  "macedonia": "North Macedonia",
  "north macedonia": "North Macedonia",

  "federal republic of germany": "Germany",
  "germany": "Germany",

  "russian federation": "Russia",
  "russia": "Russia",

  "czech republic": "Czech Republic",
  "czechia": "Czech Republic",

  "the netherlands": "Netherlands",
  "holland": "Netherlands",
  "netherlands": "Netherlands",

  // === Identity mappings ===
  "denmark": "Denmark",
  "france": "France",
  "italy": "Italy",
  "japan": "Japan",
  "spain": "Spain",
  "sweden": "Sweden",
  "norway": "Norway",
  "finland": "Finland",
  "australia": "Australia",
  "canada": "Canada",
  "brazil": "Brazil",
  "india": "India",
  "israel": "Israel",
  "turkey": "Turkey",
  "türkiye": "Turkey",
  "egypt": "Egypt",
  "saudi arabia": "Saudi Arabia",
  "iran": "Iran",
  "iraq": "Iraq",
  "pakistan": "Pakistan",
  "south africa": "South Africa",
  "nigeria": "Nigeria",
  "argentina": "Argentina",
  "mexico": "Mexico",
  "colombia": "Colombia",
  "chile": "Chile",
  "taiwan": "Taiwan",
  "singapore": "Singapore",
  "hong kong": "Hong Kong",
  "thailand": "Thailand",
  "indonesia": "Indonesia",
  "malaysia": "Malaysia",
  "philippines": "Philippines",
  "vietnam": "Vietnam",
  "new zealand": "New Zealand",
  "ireland": "Ireland",
  "belgium": "Belgium",
  "switzerland": "Switzerland",
  "austria": "Austria",
  "poland": "Poland",
  "portugal": "Portugal",
  "greece": "Greece",
  "hungary": "Hungary",
  "romania": "Romania",
  "croatia": "Croatia",
  "serbia": "Serbia",
  "bulgaria": "Bulgaria",
  "slovakia": "Slovakia",
  "slovenia": "Slovenia",
  "estonia": "Estonia",
  "latvia": "Latvia",
  "lithuania": "Lithuania",
  "ukraine": "Ukraine",
  "georgia": "Georgia",
  "kazakhstan": "Kazakhstan",
  "uzbekistan": "Uzbekistan",
  "peru": "Peru",
  "venezuela": "Venezuela",
  "ecuador": "Ecuador",
  "uruguay": "Uruguay",
  "paraguay": "Paraguay",
  "bolivia": "Bolivia",
  "cuba": "Cuba",
  "dominican republic": "Dominican Republic",
  "jamaica": "Jamaica",
  "costa rica": "Costa Rica",
  "panama": "Panama",
  "guatemala": "Guatemala",
  "honduras": "Honduras",
  "el salvador": "El Salvador",
  "nicaragua": "Nicaragua",
  "puerto rico": "Puerto Rico",
  "morocco": "Morocco",
  "tunisia": "Tunisia",
  "algeria": "Algeria",
  "libya": "Libya",
  "kenya": "Kenya",
  "ethiopia": "Ethiopia",
  "ghana": "Ghana",
  "tanzania": "Tanzania",
  "uganda": "Uganda",
  "mozambique": "Mozambique",
  "cameroon": "Cameroon",
  "senegal": "Senegal",
  "ivory coast": "Ivory Coast",
  "lebanon": "Lebanon",
  "jordan": "Jordan",
  "syria": "Syria",
  "yemen": "Yemen",
  "oman": "Oman",
  "qatar": "Qatar",
  "bahrain": "Bahrain",
  "kuwait": "Kuwait",
  "united arab emirates": "United Arab Emirates",
  "uae": "United Arab Emirates",
  "afghanistan": "Afghanistan",
  "bangladesh": "Bangladesh",
  "sri lanka": "Sri Lanka",
  "nepal": "Nepal",
  "myanmar": "Myanmar",
  "cambodia": "Cambodia",
  "laos": "Laos",
  "mongolia": "Mongolia",
  "north korea": "North Korea",
  "cyprus": "Cyprus",
  "malta": "Malta",
  "luxembourg": "Luxembourg",
  "iceland": "Iceland",
  "albania": "Albania",
  "montenegro": "Montenegro",
  "bosnia and herzegovina": "Bosnia and Herzegovina",
  "kosovo": "Kosovo",
  "moldova": "Moldova",
  "belarus": "Belarus",
  "armenia": "Armenia",
  "azerbaijan": "Azerbaijan",
  "turkmenistan": "Turkmenistan",
  "tajikistan": "Tajikistan",
  "kyrgyzstan": "Kyrgyzstan",

  // US state full names → "United States"
  "texas": "United States",
  "california": "United States",
  "new york": "United States",
  "florida": "United States",
  "illinois": "United States",
  "pennsylvania": "United States",
  "ohio": "United States",
  "michigan": "United States",
  "massachusetts": "United States",
  "minnesota": "United States",
  "maryland": "United States",
  "virginia": "United States",
  "connecticut": "United States",
  "oklahoma": "United States",
  "wisconsin": "United States",
  "colorado": "United States",
  "oregon": "United States",
  "washington": "United States",
  "tennessee": "United States",
  "indiana": "United States",
  "missouri": "United States",
  "arizona": "United States",
  "north carolina": "United States",
  "south carolina": "United States",
  "alabama": "United States",
  "louisiana": "United States",
  "kentucky": "United States",
  "iowa": "United States",
  "utah": "United States",
  "nebraska": "United States",
  "kansas": "United States",
  "nevada": "United States",
  "new jersey": "United States",
  "new hampshire": "United States",
  "new mexico": "United States",
  "hawaii": "United States",
  "maine": "United States",
  "vermont": "United States",
  "rhode island": "United States",
  "delaware": "United States",
  "montana": "United States",
  "idaho": "United States",
  "wyoming": "United States",
  "west virginia": "United States",
  "arkansas": "United States",
  "mississippi": "United States",
  "north dakota": "United States",
  "south dakota": "United States",
  "alaska": "United States",
  "district of columbia": "United States",
};

/** Case-insensitive country lookup. Handles trailing dots/whitespace. */
export function lookupCountry(raw: string): string | null {
  const cleaned = raw.replace(/\.+$/, "").trim().toLowerCase();
  return RAW_COUNTRY_MAP[cleaned] ?? null;
}

/** All canonical country names (unique values) for substring matching */
export const CANONICAL_COUNTRIES: string[] = [...new Set(Object.values(RAW_COUNTRY_MAP))];

/** US state abbreviations → full name */
export const US_STATES: Record<string, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District of Columbia",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};
