/**
 * City-to-state/province mapping for major countries.
 * Case-insensitive on city name, exact match on country.
 * No imports — pure data + lookup function.
 */

type StateEntry = Record<string, string>;

const US: StateEntry = {
  // Top 80+ US cities
  "ann arbor": "Michigan",
  "atlanta": "Georgia",
  "aurora": "Colorado",
  "baltimore": "Maryland",
  "bethesda": "Maryland",
  "birmingham": "Alabama",
  "boston": "Massachusetts",
  "bronx": "New York",
  "brooklyn": "New York",
  "buffalo": "New York",
  "burlington": "Vermont",
  "camden": "New Jersey",
  "carmel": "Indiana",
  "chapel hill": "North Carolina",
  "charleston": "South Carolina",
  "charlotte": "North Carolina",
  "charlottesville": "Virginia",
  "chicago": "Illinois",
  "cincinnati": "Ohio",
  "cleveland": "Ohio",
  "columbus": "Ohio",
  "dallas": "Texas",
  "danville": "Pennsylvania",
  "dayton": "Ohio",
  "denver": "Colorado",
  "des moines": "Iowa",
  "detroit": "Michigan",
  "durham": "North Carolina",
  "el paso": "Texas",
  "fort worth": "Texas",
  "gainesville": "Florida",
  "galveston": "Texas",
  "grand rapids": "Michigan",
  "hershey": "Pennsylvania",
  "honolulu": "Hawaii",
  "houston": "Texas",
  "indianapolis": "Indiana",
  "iowa city": "Iowa",
  "irvine": "California",
  "jackson": "Mississippi",
  "jacksonville": "Florida",
  "kansas city": "Missouri",
  "la jolla": "California",
  "las vegas": "Nevada",
  "lexington": "Kentucky",
  "little rock": "Arkansas",
  "loma linda": "California",
  "long beach": "California",
  "los angeles": "California",
  "louisville": "Kentucky",
  "madison": "Wisconsin",
  "manhasset": "New York",
  "maywood": "Illinois",
  "memphis": "Tennessee",
  "miami": "Florida",
  "milwaukee": "Wisconsin",
  "minneapolis": "Minnesota",
  "morgantown": "West Virginia",
  "nashville": "Tennessee",
  "new haven": "Connecticut",
  "new orleans": "Louisiana",
  "new york": "New York",
  "newark": "New Jersey",
  "norfolk": "Virginia",
  "oklahoma city": "Oklahoma",
  "omaha": "Nebraska",
  "orange": "California",
  "orlando": "Florida",
  "palo alto": "California",
  "philadelphia": "Pennsylvania",
  "phoenix": "Arizona",
  "pittsburgh": "Pennsylvania",
  "portland": "Oregon",
  "providence": "Rhode Island",
  "raleigh": "North Carolina",
  "richmond": "Virginia",
  "rochester": "Minnesota",
  "sacramento": "California",
  "salt lake city": "Utah",
  "san antonio": "Texas",
  "san diego": "California",
  "san francisco": "California",
  "san jose": "California",
  "seattle": "Washington",
  "shreveport": "Louisiana",
  "springfield": "Illinois",
  "st. louis": "Missouri",
  "st louis": "Missouri",
  "stanford": "California",
  "stony brook": "New York",
  "tampa": "Florida",
  "temple": "Texas",
  "tucson": "Arizona",
  "valhalla": "New York",
  "winston-salem": "North Carolina",
  "worcester": "Massachusetts",
  // Additional well-known medical/research cities
  "albuquerque": "New Mexico",
  "anchorage": "Alaska",
  "augusta": "Georgia",
  "baton rouge": "Louisiana",
  "berkeley": "California",
  "bethlehem": "Pennsylvania",
  "boise": "Idaho",
  "bridgeport": "Connecticut",
  "bronxville": "New York",
  "charlestown": "Massachusetts",
  "cooperstown": "New York",
  "coral gables": "Florida",
  "davis": "California",
  "east lansing": "Michigan",
  "evanston": "Illinois",
  "farmington": "Connecticut",
  "fort lauderdale": "Florida",
  "greenville": "South Carolina",
  "hanover": "New Hampshire",
  "hartford": "Connecticut",
  "ithaca": "New York",
  "knoxville": "Tennessee",
  "lancaster": "Pennsylvania",
  "lubbock": "Texas",
  "marshfield": "Wisconsin",
  "new brunswick": "New Jersey",
  "new rochelle": "New York",
  "northwell": "New York",
  "oakland": "California",
  "pasadena": "California",
  "peoria": "Illinois",
  "reno": "Nevada",
  "riverside": "California",
  "roanoke": "Virginia",
  "rockville": "Maryland",
  "saint louis": "Missouri",
  "sarasota": "Florida",
  "savannah": "Georgia",
  "scottsdale": "Arizona",
  "sioux falls": "South Dakota",
  "spokane": "Washington",
  "syracuse": "New York",
  "toledo": "Ohio",
  "tulsa": "Oklahoma",
  "waco": "Texas",
  "washington": "District of Columbia",
};

const CHINA: StateEntry = {
  "beijing": "Beijing",
  "shanghai": "Shanghai",
  "tianjin": "Tianjin",
  "chongqing": "Chongqing",
  "guangzhou": "Guangdong",
  "shenzhen": "Guangdong",
  "zhuhai": "Guangdong",
  "dongguan": "Guangdong",
  "foshan": "Guangdong",
  "zhongshan": "Guangdong",
  "chengdu": "Sichuan",
  "wuhan": "Hubei",
  "hangzhou": "Zhejiang",
  "ningbo": "Zhejiang",
  "wenzhou": "Zhejiang",
  "nanjing": "Jiangsu",
  "suzhou": "Jiangsu",
  "wuxi": "Jiangsu",
  "xuzhou": "Jiangsu",
  "changzhou": "Jiangsu",
  "nantong": "Jiangsu",
  "xi'an": "Shaanxi",
  "xian": "Shaanxi",
  "changsha": "Hunan",
  "harbin": "Heilongjiang",
  "zhengzhou": "Henan",
  "nanchang": "Jiangxi",
  "jinan": "Shandong",
  "qingdao": "Shandong",
  "fuzhou": "Fujian",
  "xiamen": "Fujian",
  "changchun": "Jilin",
  "kunming": "Yunnan",
  "hefei": "Anhui",
  "shenyang": "Liaoning",
  "dalian": "Liaoning",
  "taiyuan": "Shanxi",
  "nanning": "Guangxi",
  "guiyang": "Guizhou",
  "lanzhou": "Gansu",
  "shijiazhuang": "Hebei",
  "tangshan": "Hebei",
  "urumqi": "Xinjiang",
  "hohhot": "Inner Mongolia",
  "yinchuan": "Ningxia",
  "xining": "Qinghai",
  "lhasa": "Tibet",
  "haikou": "Hainan",
};

const JAPAN: StateEntry = {
  "tokyo": "Tokyo",
  "osaka": "Osaka",
  "nagoya": "Aichi",
  "fukuoka": "Fukuoka",
  "hiroshima": "Hiroshima",
  "sapporo": "Hokkaido",
  "kobe": "Hyogo",
  "kyoto": "Kyoto",
  "sendai": "Miyagi",
  "niigata": "Niigata",
  "yokohama": "Kanagawa",
  "kawasaki": "Kanagawa",
  "okayama": "Okayama",
  "kumamoto": "Kumamoto",
  "kagoshima": "Kagoshima",
  "nara": "Nara",
  "matsumoto": "Nagano",
  "nagano": "Nagano",
  "kanazawa": "Ishikawa",
  "nagasaki": "Nagasaki",
  "gifu": "Gifu",
  "toyama": "Toyama",
  "akita": "Akita",
  "morioka": "Iwate",
  "maebashi": "Gunma",
  "utsunomiya": "Tochigi",
  "mito": "Ibaraki",
  "tsukuba": "Ibaraki",
  "wakayama": "Wakayama",
  "tsu": "Mie",
  "chiba": "Chiba",
  "saitama": "Saitama",
  "shizuoka": "Shizuoka",
  "hamamatsu": "Shizuoka",
  "oita": "Oita",
  "tokushima": "Tokushima",
  "kochi": "Kochi",
  "matsuyama": "Ehime",
  "saga": "Saga",
  "yamagata": "Yamagata",
  "fukushima": "Fukushima",
  "aomori": "Aomori",
  "naha": "Okinawa",
  "takamatsu": "Kagawa",
  "tottori": "Tottori",
  "matsue": "Shimane",
  "yamaguchi": "Yamaguchi",
  "fukui": "Fukui",
  "otsu": "Shiga",
  "asahikawa": "Hokkaido",
  "hakodate": "Hokkaido",
};

const CANADA: StateEntry = {
  "toronto": "Ontario",
  "ottawa": "Ontario",
  "kingston": "Ontario",
  "hamilton": "Ontario",
  "london": "Ontario",
  "thunder bay": "Ontario",
  "sudbury": "Ontario",
  "waterloo": "Ontario",
  "guelph": "Ontario",
  "mississauga": "Ontario",
  "vancouver": "British Columbia",
  "victoria": "British Columbia",
  "kelowna": "British Columbia",
  "montreal": "Quebec",
  "montréal": "Quebec",
  "québec": "Quebec",
  "quebec city": "Quebec",
  "sherbrooke": "Quebec",
  "laval": "Quebec",
  "calgary": "Alberta",
  "edmonton": "Alberta",
  "winnipeg": "Manitoba",
  "halifax": "Nova Scotia",
  "saskatoon": "Saskatchewan",
  "regina": "Saskatchewan",
  "st. john's": "Newfoundland and Labrador",
  "st john's": "Newfoundland and Labrador",
  "charlottetown": "Prince Edward Island",
  "fredericton": "New Brunswick",
  "moncton": "New Brunswick",
  "saint john": "New Brunswick",
};

const INDIA: StateEntry = {
  "mumbai": "Maharashtra",
  "pune": "Maharashtra",
  "nagpur": "Maharashtra",
  "new delhi": "Delhi",
  "delhi": "Delhi",
  "bangalore": "Karnataka",
  "bengaluru": "Karnataka",
  "manipal": "Karnataka",
  "chennai": "Tamil Nadu",
  "vellore": "Tamil Nadu",
  "coimbatore": "Tamil Nadu",
  "madurai": "Tamil Nadu",
  "kolkata": "West Bengal",
  "hyderabad": "Telangana",
  "secunderabad": "Telangana",
  "ahmedabad": "Gujarat",
  "surat": "Gujarat",
  "vadodara": "Gujarat",
  "jaipur": "Rajasthan",
  "jodhpur": "Rajasthan",
  "lucknow": "Uttar Pradesh",
  "varanasi": "Uttar Pradesh",
  "aligarh": "Uttar Pradesh",
  "chandigarh": "Chandigarh",
  "thiruvananthapuram": "Kerala",
  "kochi": "Kerala",
  "kozhikode": "Kerala",
  "bhopal": "Madhya Pradesh",
  "indore": "Madhya Pradesh",
  "patna": "Bihar",
  "guwahati": "Assam",
  "ludhiana": "Punjab",
  "amritsar": "Punjab",
  "pondicherry": "Puducherry",
  "puducherry": "Puducherry",
  "bhubaneswar": "Odisha",
  "ranchi": "Jharkhand",
  "dehradun": "Uttarakhand",
  "shimla": "Himachal Pradesh",
  "jammu": "Jammu and Kashmir",
  "srinagar": "Jammu and Kashmir",
  "imphal": "Manipur",
  "gangtok": "Sikkim",
  "raipur": "Chhattisgarh",
};

const BRAZIL: StateEntry = {
  "são paulo": "São Paulo",
  "sao paulo": "São Paulo",
  "campinas": "São Paulo",
  "ribeirão preto": "São Paulo",
  "ribeirao preto": "São Paulo",
  "botucatu": "São Paulo",
  "santos": "São Paulo",
  "sorocaba": "São Paulo",
  "rio de janeiro": "Rio de Janeiro",
  "niterói": "Rio de Janeiro",
  "niteroi": "Rio de Janeiro",
  "salvador": "Bahia",
  "belo horizonte": "Minas Gerais",
  "uberlândia": "Minas Gerais",
  "uberaba": "Minas Gerais",
  "fortaleza": "Ceará",
  "curitiba": "Paraná",
  "londrina": "Paraná",
  "maringá": "Paraná",
  "porto alegre": "Rio Grande do Sul",
  "pelotas": "Rio Grande do Sul",
  "brasília": "Distrito Federal",
  "brasilia": "Distrito Federal",
  "recife": "Pernambuco",
  "joão pessoa": "Paraíba",
  "joao pessoa": "Paraíba",
  "aracaju": "Sergipe",
  "vitória": "Espírito Santo",
  "vitoria": "Espírito Santo",
  "florianópolis": "Santa Catarina",
  "florianopolis": "Santa Catarina",
  "belém": "Pará",
  "belem": "Pará",
  "manaus": "Amazonas",
  "campo grande": "Mato Grosso do Sul",
  "goiânia": "Goiás",
  "goiania": "Goiás",
  "natal": "Rio Grande do Norte",
  "teresina": "Piauí",
  "maceió": "Alagoas",
  "cuiabá": "Mato Grosso",
  "são luís": "Maranhão",
  "sao luis": "Maranhão",
};

const AUSTRALIA: StateEntry = {
  "melbourne": "Victoria",
  "clayton": "Victoria",
  "parkville": "Victoria",
  "heidelberg": "Victoria",
  "fitzroy": "Victoria",
  "sydney": "New South Wales",
  "burwood": "New South Wales",
  "callaghan": "New South Wales",
  "new lambton heights": "New South Wales",
  "glebe": "New South Wales",
  "liverpool": "New South Wales",
  "westmead": "New South Wales",
  "randwick": "New South Wales",
  "darlinghurst": "New South Wales",
  "camperdown": "New South Wales",
  "adelaide": "South Australia",
  "bedford park": "South Australia",
  "brisbane": "Queensland",
  "south brisbane": "Queensland",
  "southport": "Queensland",
  "herston": "Queensland",
  "woolloongabba": "Queensland",
  "perth": "Western Australia",
  "nedlands": "Western Australia",
  "murdoch": "Western Australia",
  "hobart": "Tasmania",
  "canberra": "Australian Capital Territory",
  "garran": "Australian Capital Territory",
  "tiwi": "Northern Territory",
  "darwin": "Northern Territory",
};

const SOUTH_KOREA: StateEntry = {
  "seoul": "Seoul",
  "busan": "Busan",
  "daegu": "Daegu",
  "incheon": "Incheon",
  "daejeon": "Daejeon",
  "gwangju": "Gwangju",
  "ulsan": "Ulsan",
  "suwon": "Gyeonggi-do",
  "seongnam": "Gyeonggi-do",
  "goyang": "Gyeonggi-do",
  "yongin": "Gyeonggi-do",
  "ansan": "Gyeonggi-do",
  "cheongju": "Chungcheongbuk-do",
  "cheonan": "Chungcheongnam-do",
  "jeonju": "Jeollabuk-do",
  "changwon": "Gyeongsangnam-do",
  "jinju": "Gyeongsangnam-do",
  "pohang": "Gyeongsangbuk-do",
  "jeju": "Jeju-do",
  "wonju": "Gangwon-do",
  "chuncheon": "Gangwon-do",
};

const GERMANY: StateEntry = {
  "berlin": "Berlin",
  "munich": "Bavaria",
  "münchen": "Bavaria",
  "hamburg": "Hamburg",
  "cologne": "North Rhine-Westphalia",
  "köln": "North Rhine-Westphalia",
  "frankfurt": "Hesse",
  "stuttgart": "Baden-Württemberg",
  "düsseldorf": "North Rhine-Westphalia",
  "dortmund": "North Rhine-Westphalia",
  "essen": "North Rhine-Westphalia",
  "leipzig": "Saxony",
  "dresden": "Saxony",
  "hanover": "Lower Saxony",
  "hannover": "Lower Saxony",
  "nuremberg": "Bavaria",
  "nürnberg": "Bavaria",
  "freiburg": "Baden-Württemberg",
  "heidelberg": "Baden-Württemberg",
  "tübingen": "Baden-Württemberg",
  "tuebingen": "Baden-Württemberg",
  "mannheim": "Baden-Württemberg",
  "göttingen": "Lower Saxony",
  "bonn": "North Rhine-Westphalia",
  "aachen": "North Rhine-Westphalia",
  "münster": "North Rhine-Westphalia",
  "kiel": "Schleswig-Holstein",
  "lübeck": "Schleswig-Holstein",
  "rostock": "Mecklenburg-Vorpommern",
  "greifswald": "Mecklenburg-Vorpommern",
  "jena": "Thuringia",
  "erlangen": "Bavaria",
  "würzburg": "Bavaria",
  "regensburg": "Bavaria",
  "augsburg": "Bavaria",
  "mainz": "Rhineland-Palatinate",
  "magdeburg": "Saxony-Anhalt",
  "halle": "Saxony-Anhalt",
  "bremen": "Bremen",
  "saarbrücken": "Saarland",
  "potsdam": "Brandenburg",
  "ulm": "Baden-Württemberg",
  "gießen": "Hesse",
  "giessen": "Hesse",
  "marburg": "Hesse",
  "bochum": "North Rhine-Westphalia",
  "wuppertal": "North Rhine-Westphalia",
  "duisburg": "North Rhine-Westphalia",
};

const UK: StateEntry = {
  "london": "England",
  "oxford": "England",
  "cambridge": "England",
  "manchester": "England",
  "birmingham": "England",
  "liverpool": "England",
  "leeds": "England",
  "sheffield": "England",
  "bristol": "England",
  "nottingham": "England",
  "newcastle": "England",
  "newcastle upon tyne": "England",
  "southampton": "England",
  "leicester": "England",
  "coventry": "England",
  "brighton": "England",
  "exeter": "England",
  "norwich": "England",
  "bath": "England",
  "york": "England",
  "plymouth": "England",
  "edinburgh": "Scotland",
  "glasgow": "Scotland",
  "aberdeen": "Scotland",
  "dundee": "Scotland",
  "cardiff": "Wales",
  "swansea": "Wales",
  "belfast": "Northern Ireland",
};

const FRANCE: StateEntry = {
  "paris": "Île-de-France",
  "lyon": "Auvergne-Rhône-Alpes",
  "marseille": "Provence-Alpes-Côte d'Azur",
  "toulouse": "Occitanie",
  "montpellier": "Occitanie",
  "bordeaux": "Nouvelle-Aquitaine",
  "lille": "Hauts-de-France",
  "strasbourg": "Grand Est",
  "nantes": "Pays de la Loire",
  "rennes": "Bretagne",
  "brest": "Bretagne",
  "nice": "Provence-Alpes-Côte d'Azur",
  "grenoble": "Auvergne-Rhône-Alpes",
  "clermont-ferrand": "Auvergne-Rhône-Alpes",
  "rouen": "Normandie",
  "caen": "Normandie",
  "dijon": "Bourgogne-Franche-Comté",
  "besançon": "Bourgogne-Franche-Comté",
  "reims": "Grand Est",
  "nancy": "Grand Est",
  "tours": "Centre-Val de Loire",
  "poitiers": "Nouvelle-Aquitaine",
  "limoges": "Nouvelle-Aquitaine",
  "amiens": "Hauts-de-France",
  "angers": "Pays de la Loire",
};

const ITALY: StateEntry = {
  "rome": "Lazio",
  "roma": "Lazio",
  "milan": "Lombardy",
  "milano": "Lombardy",
  "naples": "Campania",
  "napoli": "Campania",
  "turin": "Piedmont",
  "torino": "Piedmont",
  "florence": "Tuscany",
  "firenze": "Tuscany",
  "bologna": "Emilia-Romagna",
  "padua": "Veneto",
  "padova": "Veneto",
  "venice": "Veneto",
  "venezia": "Veneto",
  "verona": "Veneto",
  "genoa": "Liguria",
  "genova": "Liguria",
  "palermo": "Sicily",
  "catania": "Sicily",
  "bari": "Apulia",
  "pisa": "Tuscany",
  "siena": "Tuscany",
  "perugia": "Umbria",
  "trieste": "Friuli-Venezia Giulia",
  "modena": "Emilia-Romagna",
  "parma": "Emilia-Romagna",
  "ferrara": "Emilia-Romagna",
  "brescia": "Lombardy",
  "bergamo": "Lombardy",
  "ancona": "Marche",
  "cagliari": "Sardinia",
  "sassari": "Sardinia",
  "l'aquila": "Abruzzo",
  "messina": "Sicily",
  "novara": "Piedmont",
  "pavia": "Lombardy",
};

const SPAIN: StateEntry = {
  "madrid": "Community of Madrid",
  "barcelona": "Catalonia",
  "valencia": "Valencian Community",
  "seville": "Andalusia",
  "sevilla": "Andalusia",
  "málaga": "Andalusia",
  "malaga": "Andalusia",
  "granada": "Andalusia",
  "córdoba": "Andalusia",
  "bilbao": "Basque Country",
  "san sebastián": "Basque Country",
  "zaragoza": "Aragon",
  "murcia": "Region of Murcia",
  "palma": "Balearic Islands",
  "las palmas": "Canary Islands",
  "santa cruz de tenerife": "Canary Islands",
  "salamanca": "Castile and León",
  "valladolid": "Castile and León",
  "santiago de compostela": "Galicia",
  "pamplona": "Navarre",
  "oviedo": "Asturias",
  "santander": "Cantabria",
};

const COUNTRY_MAPS: Record<string, StateEntry> = {
  "United States": US,
  "China": CHINA,
  "Japan": JAPAN,
  "Canada": CANADA,
  "India": INDIA,
  "Brazil": BRAZIL,
  "Australia": AUSTRALIA,
  "South Korea": SOUTH_KOREA,
  "Germany": GERMANY,
  "United Kingdom": UK,
  "France": FRANCE,
  "Italy": ITALY,
  "Spain": SPAIN,
};

/**
 * Lookup state/province for a city+country pair.
 * Case-insensitive on city. Country must be canonical name.
 * Returns state/province name or null.
 */
export function lookupState(city: string, country: string): string | null {
  const map = COUNTRY_MAPS[country];
  if (!map) return null;
  return map[city.trim().toLowerCase()] ?? null;
}
