export const SUBSPECIALTY_OPTIONS = [
  "Spine surgery",
  "Neurosurgical oncology and Radiosurgery",
  "Vascular and Endovascular Neurosurgery",
  "Functional, pain and epilepsy surgery",
  "Pediatric and foetal neurosurgery",
  "Neurotraumatology",
  "Peripheral nerve surgery",
  "Skull base and pituitary surgery",
  "Craniofacial and reconstruction surgery",
  "Geriatric Neurosurgery",
  "Hydrocephalus and CSF Disorders",
  "Neurointensive care and Neuroinfection",
  "Neurorehabilitation",
  "Surgical Technique and Technology",
  "Basic and Translational Research",
  "Ethics, Education and Socioeconomics",
  "Digital Health, Robotics, and Innovation",
] as const;
