export const SUBSPECIALTY_OPTIONS = [
  "Spine surgery",
  "Neurosurgical oncology and Radiosurgery",
  "Vascular and Endovascular Neurosurgery",
  "Functional, pain and epilepsy surgery",
  "Pediatric and foetal neurosurgery",
  "Neurotraumatology",
  "Peripheral nerve surgery",
  "Skull base and pituitary surgery",
  "Craniofacial and reconstruction surgery",
  "Geriatric Neurosurgery",
  "Hydrocephalus and CSF Disorders",
  "Neurointensive care and Neuroinfection",
  "Neurorehabilitation",
  "Surgical Technique and Technology",
  "Basic and Translational Research",
  "Ethics, Education and Socioeconomics",
  "Digital Health, Robotics, and Innovation",
] as const;

export const ARTICLE_TYPE_OPTIONS = [
  "RCT",
  "Meta-analysis",
  "Systematic Review",
  "Narrative Review",
  "Prospective Cohort",
  "Retrospective Cohort",
  "Case Series",
  "Case Report",
  "Technical Note",
  "Guideline",
  "Regulatory Update",
  "Editorial/Commentary",
  "Letter",
] as const;

export const STUDY_DESIGN_OPTIONS = [
  "Randomized controlled",
  "Prospective observational",
  "Retrospective observational",
  "Cross-sectional",
  "Case-control",
  "Systematic review",
  "Meta-analysis",
  "In vitro/preclinical",
  "Registry-based",
  "Qualitative",
  "Not applicable",
] as const;
